version: "3.7"

services:
  app:
    build: ./app
    ports:
      - 4200:4200
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - api
    container_name: app_seed
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongo
    container_name: api_seed
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
